apiVersion: apps/v1
kind: Deployment
metadata:
  name: processTask
  labels:
    app: processTask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processTask
  template:
    metadata:
      labels:
        app: processTask
    spec:
      containers:
        - name: processTask
          image: username/processTask:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5